apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mvfm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mvfm
    app.kubernetes.io/part-of: ci1t-830-0069-app
  name: devfile-sample-mvfm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mvfm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mvfm
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0069-tenant/ci1t-830-0069-app/devfile-sample-mvfm@sha256:7c7c4974f3372f37e5118bb691639f46836910e0cb1368c280282d180b9353d3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
